int nbre_etudiant();
int nbre_sujets();
int auth();
void charger_donnees(Etudiant*, Pres*);
int comparateur_e(const void* p, const void* q);
int comparateur_s(const void* p, const void* q);
char* fetch_sujet(Etudiant* e, Pres* p);
void trier_e(Etudiant* e);
void trier_s(Pres* e);
void afficher_etudiants(Etudiant* e, Pres* p);
void afficher_sujets(Etudiant* e, Pres* p);
int verifier_etudiant(Etudiant*, Etudiant*, int);
void sauvegarder_etudiant(Etudiant*, int);
void ajouter_etudiant(Etudiant* e);
Etudiant* selectionner_etudiant(Etudiant* e);
void modifier_etudiant(Etudiant* e);
void supp_etudiant(Etudiant* e);
void chercher_etudiant(Etudiant* e, Pres* p);
int der_sujet_id(Pres* p);
void sauvegarder_sujet(Pres*, int);
void ajouter_sujet(Pres* p);
void modifier_sujet(Pres* p);
int fetch_etudiant(Etudiant* e, Pres* p);
int* afficher_sujets_disp(Etudiant* e, Pres* p);
void chercher_sujet(Etudiant* e, Pres* p);
void supp_sujet(Etudiant* e, Pres* p);
Pres* chercher_p(Pres* p, int x);
int* afficher_pres_afaire(Etudiant* e, Pres* p);
Etudiant* chercher_e(Etudiant* e, int x);
void fait(Etudiant* e, Pres* p) ;
void abandonner(Etudiant* e);
void changer_presenteur(Etudiant* e, Pres* p);
void retour();
void fordelay(int j);
int verifier_choix(int* choices, int choix, int n);
int nbre_etudiant_ajouter();
int nbre_sujets_ajouter();
